version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      cache_from:
        - webapp_nginx:latest
    image:  webapp_nginx:latest
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
      - type: bind
        source: ./docker/certbot/letsencrypt/ssl-dhparams.pem
        target: /etc/letsencrypt/ssl-dhparams.pem
        volume:
          nocopy: true
      - type: bind
        source: ./docker/certbot/letsencrypt/options-ssl-nginx.conf
        target: /etc/letsencrypt/options-ssl-nginx.conf
        volume:
          nocopy: true
      - type: bind
        source: ./scripts/nginx_entrypoint.sh
        target: /entrypoint.sh
        volume:
          nocopy: true
    entrypoint: "./entrypoint.sh"
    ports:
      - "80:80"
      - "443:443"