version: '3'
services:
  nginx:
    image: "nginx:1.17.3"
    volumes:
      - type: "bind"
        sorce: "logs/nginx"
        target: "/var/log/nginx"
      - type: "bind"
        source: "docker/nginx/conf.d"
        target: "/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  certbot:
    image: "certbot/certbot"
    depends_on:
      - "nginx"