version: '3.7'
services:
  nginx:
    image: "nginx:1.17.3"
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
      - type: bind
          source: ./docker/certbot/conf
          target: /etc/letsencrypt
          volume:
            nocopy: true
      - type: bind
          source: ./docker/certbot/www
          target: /var/www/certbot
          volume:
            nocopy: true
      - type: bind
          source: ./scripts/init-letsencrypt.sh
          target: /etc/nginx/init-letsencrypt.sh
          volume:
            nocopy: true
    entrypoint: "/bin/sh -c 'chmod +x /etc/nginx/init-letsencrypt.sh and /etc/nginx/init-letsencrypt.sh && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: "certbot/certbot"
    depends_on:
      - "nginx"
    volumes:
      - type: bind
          source: ./docker/certbot/conf
          target: /etc/letsencrypt
          volume:
            nocopy: true
      - type: bind
          source: ./docker/certbot/www
          target: /var/www/certbot
          volume:
            nocopy: true
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"