version: '3.7'
services:
  nginx:
    image: "nginx:1.17.3"
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: "certbot/certbot"
    depends_on:
      - "nginx"