version: '3.7'
services:
  app:
    container_name: webapp
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      cache_from:
        - webapp_nginx:latest
    image:  webapp_nginx:latest
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d_new
        volume:
          nocopy: true
      - type: bind
        source: ./scripts/entrypoint.sh
        target: /./entrypoint.sh
        volume:
          nocopy: true
      - type: bind
        source: ./app
        target: /app
        volume:
          nocopy: true
      - type: bind
        source: ./keys
        target: /keys
        volume:
          nocopy: true
    entrypoint: "sudo /entrypoint.sh"
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"