version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
      - type: bind
        source: ./docker/certbot/conf/ssl-dhparams.pem
        target: /etc/letsencrypt/ssl-dhparams.pem
        volume:
          nocopy: true
      - type: bind
          source: ./docker/certbot/conf/options-ssl-nginx.conf
          target: /etc/letsencrypt/options-ssl-nginx.conf
          volume:
            nocopy: true
    entrypoint: "nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"