version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
      - type: bind
        source: ./docker/certbot/letsencrypt/ssl-dhparams.pem
        target: /etc/letsencrypt/ssl-dhparams.pem
        volume:
          nocopy: true
      - type: bind
        source: ./docker/certbot/letsencrypt/options-ssl-nginx.conf
        target: /etc/letsencrypt/options-ssl-nginx.conf
        volume:
          nocopy: true
    restart_policy:
      condition: on-failure
    entrypoint: >
      "openssl req -x509 -nodes -newkey rsa:1024 -days 1"
      "-keyout /etc/letsencrypt/live/the-software.dev/privkey.pem'"
      "-out /etc/letsencrypt/live/the-software.dev/fullchain.pem -subj '/CN=localhost"
      "&& nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"