version: '3.7'
services:
  webapp:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
      cache_from:
        - webapp_app:latest
    image:  webapp_app:latest
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
      - type: bind
        source: ./scripts/nginx_entrypoint.sh
        target: /entrypoint.sh
        volume:
          nocopy: true
    entrypoint: "./entrypoint.sh"
    ports:
      - "80:80"
      - "443:443"