version: '3.7'
services:
  webapp:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
      cache_from:
        - webapp_app:latest
    image:  webapp_app:latest
    volumes:
      - type: bind
        source: ./app
        target: /app
        volume:
          nocopy: true
      - type: bind
        source: ./scripts/webapp_entrypoint.sh
        target: /entrypoint.sh
        volume:
          nocopy: true
    entrypoint: "./entrypoint.sh"
    ports:
      - "5000:5000"